
name: Build and Publish

# Trigger this workflow only when the main branches, assets folder is modified.
on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/smashtests.yml'
      - 'tests/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -  uses: actions/setup-node@v3
      - name: Install git
        run: sudo apt-get install -y git
      - run: npm install
      - run: npx eleventy
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
